### ISSUE TITLE
feat: add an option to run github actions and upload to onedrive

### ISSUE THREAD

**Issue by thenicekat** [pnicto/impartus-video-downloader#27]
Proposed workflow?
1. People will have the ability to fork this repo and in environment set variables for their onedrive key 
2. Github action will download video and upload to onedrive (Should be doable with free limits i guess)
3. Github action could be triggerable or even automatic (i am not sure if github action has such an option)

**Comment by pnicto** [comment]
On thinking, I do not see much value in this feature. Hence, I am marking it as not planned. Here's my rationale for the same:

- Having videos locally is more accessible than having them on one drive, except where you want to view the videos on your phone and don't want to use your phone storage. But that can be dealt with easily by uploading whatever you want to one drive yourself.
- The github hosted runners have storage limits ([source](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)), this requires some changes in the workflow where each time the action is run, it can only do some videos at a time. I find the input cumbersome as you have to modify the workflow file (or some config file) specifying which videos to download every time when you want to download.
- Dealing with one drive API is painful.
- Lastly, the number of people using this will be in single digits(likely 0) because this involves jumping through many hoops like getting an access token from one drive, having a GitHub account(very hard for students from engineering college :D), and forking and setting up everything. From my experience of making erp2gcal, I see that people find the steps cumbersome, hard, annoying, and whatnot.

This could be interesting when combined with the automated workflows (GitHub actions can be triggered periodically), but I find the option of having all these videos on DC++ more attractive. Another reason is instead of every person having the same video files of a course(redundant), they could have different courses and together serve as a single complete catalog.
