### ISSUE TITLE
Slides always saving in the same folder

### ISSUE THREAD

**Issue by HemanthK-12** [pnicto/impartus-video-downloader#28]
### Description
When the slides boolean is set to true in the config.json file, the slides are saved to the current working directory (the folder where the impartus_video_downloader executable is present), even though the path specified in the downloadLocation is changed.

## Steps to Reproduce
- Set the slides field to true and a different downloadLocation path in config.json.
- Run the impartus_video_downloader executable and download any lecture.
- Slides are saved in the current working directory instead of the specified downloadLocation.

## Expected Behavior
Slides should be saved in the directory specified by the downloadLocation field in the config.json file.

## Actual Behavior
Slides are saved in the current working directory where the executable is located, ignoring the downloadLocation setting.

My env : Debian 12, downloader latest version.

**Comment by pnicto** [comment]
The `downloadLocation` in `config.json` is valid only for video files. Downloading slides was always an extra feature(I didn't know anyone who uses it and I don't use it either), which I didn't flesh out properly. The slides destination folder is hardcoded as I didn't want to bother thinking about what would be a nice location for slides (I just wanted slides for one course in my 3.5 years).

As for the expected behavior you stated I do not completely agree with you on `slides` folder being in the root of `downloadLocation` path.

Like according to the expected behaviour you stated, this will be the file tree:
```
downloadLocation
├── slides
│   └── course1/ # slides here
└── course1/ # videos here
```

I think slides should just be created in a slides folder inside the respective course video folders, for example:

```
downloadLocation
└── course1
    ├── slides # folder with slides
    └── # all the videos
```

But at the same time I am not keen on the 2nd implementation either. Since I didn't want to decide I deferred it. If you have some ideas you can propose them and later after discussing if possible make a PR implementing it. Currently this project is not a priority to me so I will take my sweet time.

The hardcoded part:
https://github.com/pnicto/impartus-video-downloader/blob/f1a82371678dc74c6bf69cb806ac3a4f2f0b7037/main.go#L66

**Comment by pnicto** [comment]
Of course, I can make a very simple change for the expected behaviour you stated; it's just that I don't like that folder structure. Since I don't download slides I can just make the change and forget about it, but I wanted to take this chance to see if there's a better way.

**Comment by HemanthK-12** [comment]
Also, why is the name of the folders in which the slides are stored, and the folder in which the lectures are stored, different?
Eg: For a specific course, slides folder is : CS F364 DESIGN & ANAL OF ALGO L1 and lecture folder is named : CS F364 DESIGN & ANAL OF ALGO L1 Jan - Jul 2023.
Won't this just group all slides of this course downloaded from different accounts into one folder? 
Please don't get me wrong, I'm trying to understand :)

**Comment by HemanthK-12** [comment]
downloadLocation
└── course1
    ├── slides # folder with slides
    └── # all the videos
 
This kind of implementation seems good and clear also, would be good if we can go ahead with this, if yes, I'll make a PR.

**Comment by pnicto** [comment]
> Also, why is the name of the folders in which the slides are stored, and the folder in which the lectures are stored, different? Eg: For a specific course, slides folder is : CS F364 DESIGN & ANAL OF ALGO L1 and lecture folder is named : CS F364 DESIGN & ANAL OF ALGO L1 Jan - Jul 2023. Won't this just group all slides of this course downloaded from different accounts into one folder? Please don't get me wrong, I'm trying to understand :)

That's a good question. The short answer is it is because of my poor planning and I forgot.

Previously, both video folders and slides folders followed the same convention, i.e., there was no semester start and end month with year in the video folder name. Later, I needed to download lectures from a different semester for the same course; that is when I realised that I needed a way to distinguish the folders, and it was also necessary to prevent overwriting videos if the folder name was not different. I completely forgot about this issue with slides💀.

And having `CS F364 DESIGN & ANAL OF ALGO L1` for slides won't group the slides, it will in fact, overwrite the previously downloaded slides as the name of files is not unique (in lectures, you may or may not encounter this issue as students update the name for lectures on impartus but the overwriting issue exists if no name is given on impartus website as the default name is "No Topic Entered").

**Comment by pnicto** [comment]
> downloadLocation └── course1    ├── slides # folder with slides    └── # all the videos
> 
> This kind of implementation seems good and clear also, would be good if we can go ahead with this, if yes, I'll make a PR.

About this, I have a third idea in mind let me know what you think about this one too. Instead of creating a folder, I think we can just have both slides and videos in the same folder. Similar to how subtitle files are present in the same directory as the videos. This looks messy, but I think it is very convenient. I can also think of a con for normal users, they won't be able to move only videos or slides easily if they want to. But "power" users will have no such problems. This shouldn't be an issue according to me.

```
downloadLocation
└── course1
    ├── L001 video1.mkv
    ├── L001 ppt.pdf
    ├── L002 video1.mkv
    ├── L002 ppt.pdf
    ├── L003 video1.mkv
    ├── L003 ppt.pdf
    ├── L004 video1.mkv
    ├── L004 ppt.pdf
    ├── L005 video1.mkv
    ├── L005 ppt.pdf
    ├── L006 video1.mkv
    └── L006 ppt.pdf
```

**Comment by HemanthK-12** [comment]
Yeah, this feels more straightforward, and we can make sure the names(or prefixes of names, I think names being same is better) of both the video and the respective slide are the same so that they appear next to each other in general file structure.(Also the normal users can get around this problem by sorting by type, so that's not that big of an issue and could be a win-win). The name could directly be the name of the lecture.
### Present Naming convention
```
├── downloads
│   └── CS F364 DESIGN & ANAL OF ALGO L1 Jan - Jul 2023
│       └── LEC 001 1- Introduction LEFT VIEW.mp4
└── slides
    └── CS F364 DESIGN & ANAL OF ALGO L1
        └── L001 1- Introduction.pdf
``` 
Changes :
- No existing sides folder now, keep the slides in the same folder as lectures.
- Name of the slides will be exactly same as it's corresponding lecture.
- (requesting change)Name of the lecture folder can also contain the name of the teaching professor since as of now, there is no way to view what professor has taken the course apart from figuring out from the lecture video.
### Proposed Naming convention
```
├── downloads
│   └── CS F364 DESIGN & ANAL OF ALGO L1 DR.TATHAGAT RAY Jan - Jul 2023
│       └── LEC 001 1- Introduction LEFT VIEW.mp4
│       └── LEC 001 1- Introduction.pdf
```

All okay with this?

**Comment by pnicto** [comment]
Sounds good to me! You can make a PR. If you face any challenges, just let me know. The code is not good as this was my first go project. If you feel overwhelmed, just leave this to me; I will make the necessary changes at my own pace.

# Changes to be made

- [ ] When the slides option is enabled in the configuration file, download slides into the same folder as the videos.
- [ ] Change the subject folder name to have the professor's name.

**Comment by HemanthK-12** [comment]
Yes, I'll submit the PR. Give me 2 days.
